name: Resources and Code Check

on:
  pull_request:

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
        working-directory: ./package

      - name: Resources check
        run: |
          cd ./package
          npm run check
          npm run build

      - run: npm ci

      - name: Code check
        run: |
          npm run lint
          npm run test
